### ISSUE TITLE
Guest Customization template in vSphere_Guest module

### ISSUE THREAD

**Issue by mmumshad** [rendicott/ansible-windows-provisoning#1]
Is it possible to apply a guest customization spec while deploying windows from template?

**Comment by rendicott** [comment]
Here is documentation for the vsphere_guest module. http://docs.ansible.com/ansible/vsphere_guest_module.html
I believe the plugin is deprecated and a lot of people recommended using pyvmomi instead.

**Comment by rendicott** [comment]
Closing this as I don't control the plugin in question.
